config:
  lr: 2.0e-05
  seed: 123
  gradient_accumulation_steps: 1
  weight_decay: 0.01
  validation_metrics:
  - MRR@10
  - recall@100
  - recall@200
  - recall@500
  pretrained_no_yamlconfig: false
  nb_iterations: 150000
  train_batch_size: 64
  eval_batch_size: 64
  index_retrieve_batch_size: 64
  record_frequency: 10000
  train_monitoring_freq: 500
  warmup_steps: 6000
  max_length: 256
  fp16: false
  matching_type: splade
  monitoring_ckpt: MRR@10
  loss: InBatchPairwiseNLL
  augment_pair: in_batch_negatives
  regularizer:
    FLOPS:
      lambda_q: 0.0005
      lambda_d: 0.0003
      T: 3
      targeted_rep: rep
      reg: FLOPS
  tokenizer_type: neuralmind/bert-base-portuguese-cased
  top_k: 1000
  threshold: 0
  eval_metric:
  - - mrr_10
    - recall
    - ndcg_cut_20
    - recall@1000
  checkpoint_dir: /content/experiments/splade_mmarco_pt_4M/checkpoint
  index_dir: /content/experiments/splade_mmarco_pt_4M/index
  out_dir: /content/experiments/splade_mmarco_pt_4M/out
data:
  type: triplets
  TRAIN_DATA_DIR: data/mmarco-pt-4M/triplets
  VALIDATION_SIZE_FOR_LOSS: 60000
  VALIDATION_FULL_RANKING:
    D_COLLECTION_PATH: data/mmarco-pt/val_collection
    Q_COLLECTION_PATH: data/mmarco-pt/val_queries
    QREL_PATH: data/mmarco-pt/qrel/qrel.json
    TOP_K: 500
  COLLECTION_PATH: data/mmarco-pt/full_collection
  Q_COLLECTION_PATH:
  - data/mmarco-pt/dev_queries
  EVAL_QREL_PATH:
  - data/mmarco-pt/dev_qrel.json
  flops_queries: data/mmarco-pt/dev_queries/
init_dict:
  model_type_or_dir: neuralmind/bert-base-portuguese-cased
  model_type_or_dir_q: null
  freeze_d_model: 0
  agg: max
  fp16: false
